### ISSUE TITLE
error on go get

### ISSUE THREAD

**Issue by fils** [knakk/sparql#1]
getting an error during go get.   
go version go1.2.1 darwin/amd64

```
Doug-Fils-MBP:officium dfils$ go get github.com/knakk/sparql
# github.com/knakk/sparql
../../github.com/knakk/sparql/repo.go:55: r.client.Timeout undefined (type *http.Client has no field or method Timeout)
```

**Comment by fils** [comment]
Sorry..  I didn't see how OLD my go install was..  updating to 1.4 resolved this.

**Comment by boutros** [comment]
Glad it worked out.

I will be making some changes in the dependant rdf package in the coming months, but I'll make sure to upate this package as well, should it be needed.
