### ISSUE TITLE
License

### ISSUE THREAD

**Issue by turbolent** [knakk/sparql#4]
It looks like this project doesn't have a license, or I couldn't find any. 
Is there any chance the code in this repository could be released as open-source and get a license file?

**Comment by boutros** [comment]
Sure!

**Comment by turbolent** [comment]
It would be great to actually add an open-source license. The current one is not stating any terms or if the code is in public domain, etc.

Maybe just pick MIT or BSD license?

**Comment by boutros** [comment]
I belive there is far too much legal speak in software, an too litle poetry

**Comment by boutros** [comment]
The terms should be clear: do as you like with this
