### ISSUE TITLE
Support SPARQL update

### ISSUE THREAD

**Issue by jcoyne** [knakk/sparql#9]
Would this be as easy as allowing method (currently `query`) to be a passed parameter (e.g. set to `update`) here? https://github.com/knakk/sparql/blob/master/repo.go#L112

**Comment by boutros** [comment]
Hi!
I'm fine with expanding the api with a `Repo.Update(q string)` method
Do you want to have a go at it?

**Comment by boutros** [comment]
:+1:

**Comment by jcoyne** [comment]
Fixed by #10
